### ISSUE TITLE
Upload failed

### ISSUE THREAD

**Issue by mariiaa28** [jasur-2902/CarRecognition#4]
Hi ! I want to do a similar app and I tried yours, but I have a problem. If I try to upload a photo or make one I have the following error : "Upload failed : The object does not exist at location". What can I do in this case? Thank you !

**Comment by jasurshukurov** [comment]
Hi Maria, due to the price, I've deprecated the API. Therefore, it won't actually recognize anything, because API Request will return 404 not found. You can use the interface and connect to any other public API
